//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiceCombats.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Automations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Automations() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiceCombats.Resources.Localization.Automations", typeof(Automations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Action name.
        /// </summary>
        public static string ActionName {
            get {
                return ResourceManager.GetString("ActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actions sequence.
        /// </summary>
        public static string ActionsSequence {
            get {
                return ResourceManager.GetString("ActionsSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Action.
        /// </summary>
        public static string ActionTitle {
            get {
                return ResourceManager.GetString("ActionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add automation.
        /// </summary>
        public static string AddAutomation {
            get {
                return ResourceManager.GetString("AddAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add Delay.
        /// </summary>
        public static string AddDelay {
            get {
                return ResourceManager.GetString("AddDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add external app.
        /// </summary>
        public static string AddExternalApp {
            get {
                return ResourceManager.GetString("AddExternalApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add HTTP Request.
        /// </summary>
        public static string AddHttpRequest {
            get {
                return ResourceManager.GetString("AddHttpRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à App name.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Assistance.
        /// </summary>
        public static string Assistance {
            get {
                return ResourceManager.GetString("Assistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actions run from left to right. Use HTTP requests to call another app and delays to pause between requests. If.
        /// </summary>
        public static string AssistanceActionsText1 {
            get {
                return ResourceManager.GetString("AssistanceActionsText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à is disabled, the remaining actions are skipped after a failed action..
        /// </summary>
        public static string AssistanceActionsText2 {
            get {
                return ResourceManager.GetString("AssistanceActionsText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 3. Actions.
        /// </summary>
        public static string AssistanceActionsTitle {
            get {
                return ResourceManager.GetString("AssistanceActionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add one automation for each independent rule. Give it a clear name, keep it enabled, then choose when it should run. Some triggers can be restricted to specific creatures, custom fields, options, stats, or numeric thresholds. Empty filters mean “any”..
        /// </summary>
        public static string AssistanceAutomationsText {
            get {
                return ResourceManager.GetString("AssistanceAutomationsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2. Automations.
        /// </summary>
        public static string AssistanceAutomationsTitle {
            get {
                return ResourceManager.GetString("AssistanceAutomationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add an external app when several HTTP actions target the same server. Set its base URL, for example.
        /// </summary>
        public static string AssistanceExternalAppsText1 {
            get {
                return ResourceManager.GetString("AssistanceExternalAppsText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à HTTP actions can then use short relative paths such as.
        /// </summary>
        public static string AssistanceExternalAppsText2 {
            get {
                return ResourceManager.GetString("AssistanceExternalAppsText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You can also skip external apps and enter an absolute URL directly in an HTTP action..
        /// </summary>
        public static string AssistanceExternalAppsText3 {
            get {
                return ResourceManager.GetString("AssistanceExternalAppsText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1. External apps.
        /// </summary>
        public static string AssistanceExternalAppsTitle {
            get {
                return ResourceManager.GetString("AssistanceExternalAppsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Press.
        /// </summary>
        public static string AssistanceSaveLogsText1 {
            get {
                return ResourceManager.GetString("AssistanceSaveLogsText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à after editing. Delivery logs at the bottom of this page show which automation ran, whether it succeeded, the HTTP status code, and possible error messages..
        /// </summary>
        public static string AssistanceSaveLogsText2 {
            get {
                return ResourceManager.GetString("AssistanceSaveLogsText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 4. Save and check logs.
        /// </summary>
        public static string AssistanceSaveLogsTitle {
            get {
                return ResourceManager.GetString("AssistanceSaveLogsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Automations let DiceCombats react to combat events. An automation watches for one trigger, then runs one or more actions in order. Typical uses are starting or stopping an external timer, notifying another tool, or sending the current creature information to a local companion app..
        /// </summary>
        public static string AssistanceWhatAutomationsDoText {
            get {
                return ResourceManager.GetString("AssistanceWhatAutomationsDoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à What automations do.
        /// </summary>
        public static string AssistanceWhatAutomationsDoTitle {
            get {
                return ResourceManager.GetString("AssistanceWhatAutomationsDoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Automation.
        /// </summary>
        public static string AutomationFallback {
            get {
                return ResourceManager.GetString("AutomationFallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Automation name.
        /// </summary>
        public static string AutomationName {
            get {
                return ResourceManager.GetString("AutomationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Automations.
        /// </summary>
        public static string AutomationsSectionTitle {
            get {
                return ResourceManager.GetString("AutomationsSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Base URL.
        /// </summary>
        public static string BaseUrl {
            get {
                return ResourceManager.GetString("BaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Body template.
        /// </summary>
        public static string BodyTemplate {
            get {
                return ResourceManager.GetString("BodyTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Comparison.
        /// </summary>
        public static string Comparison {
            get {
                return ResourceManager.GetString("Comparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Continue on failure.
        /// </summary>
        public static string ContinueOnFailure {
            get {
                return ResourceManager.GetString("ContinueOnFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Creatures (empty = any creature).
        /// </summary>
        public static string CreaturesEmptyAnyCreature {
            get {
                return ResourceManager.GetString("CreaturesEmptyAnyCreature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Custom field (empty = any matching field).
        /// </summary>
        public static string CustomFieldEmptyAnyMatchingField {
            get {
                return ResourceManager.GetString("CustomFieldEmptyAnyMatchingField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delay.
        /// </summary>
        public static string DefaultDelayName {
            get {
                return ResourceManager.GetString("DefaultDelayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à HTTP request.
        /// </summary>
        public static string DefaultHttpRequestName {
            get {
                return ResourceManager.GetString("DefaultHttpRequestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delay milliseconds.
        /// </summary>
        public static string DelayMilliseconds {
            get {
                return ResourceManager.GetString("DelayMilliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete action.
        /// </summary>
        public static string DeleteAction {
            get {
                return ResourceManager.GetString("DeleteAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete automation.
        /// </summary>
        public static string DeleteAutomation {
            get {
                return ResourceManager.GetString("DeleteAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delivery logs.
        /// </summary>
        public static string DeliveryLogs {
            get {
                return ResourceManager.GetString("DeliveryLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à End.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Endpoint absolute URL.
        /// </summary>
        public static string EndpointAbsoluteUrl {
            get {
                return ResourceManager.GetString("EndpointAbsoluteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Endpoint relative path.
        /// </summary>
        public static string EndpointRelativePath {
            get {
                return ResourceManager.GetString("EndpointRelativePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à End.
        /// </summary>
        public static string EndTitle {
            get {
                return ResourceManager.GetString("EndTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Event data placeholders.
        /// </summary>
        public static string EventDataPlaceholdersTitle {
            get {
                return ResourceManager.GetString("EventDataPlaceholdersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Event.
        /// </summary>
        public static string EventTitle {
            get {
                return ResourceManager.GetString("EventTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à On the creature custom field, enable the numeric maximum value display first. Then create an automation with trigger.
        /// </summary>
        public static string ExampleNumericMaxText1 {
            get {
                return ResourceManager.GetString("ExampleNumericMaxText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select the relevant creature and field, or leave them empty to react to any matching field..
        /// </summary>
        public static string ExampleNumericMaxText2 {
            get {
                return ResourceManager.GetString("ExampleNumericMaxText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Example: react when a numeric field reaches its maximum.
        /// </summary>
        public static string ExampleNumericMaxTitle {
            get {
                return ResourceManager.GetString("ExampleNumericMaxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create an external app named.
        /// </summary>
        public static string ExampleTimerText1 {
            get {
                return ResourceManager.GetString("ExampleTimerText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à with base URL.
        /// </summary>
        public static string ExampleTimerText2 {
            get {
                return ResourceManager.GetString("ExampleTimerText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Then create an automation with trigger.
        /// </summary>
        public static string ExampleTimerText3 {
            get {
                return ResourceManager.GetString("ExampleTimerText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à and add an HTTP POST action to.
        /// </summary>
        public static string ExampleTimerText4 {
            get {
                return ResourceManager.GetString("ExampleTimerText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Example: send the active creature to an external timer.
        /// </summary>
        public static string ExampleTimerTitle {
            get {
                return ResourceManager.GetString("ExampleTimerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à None (use absolute URL).
        /// </summary>
        public static string ExternalAppNoneAbsolute {
            get {
                return ResourceManager.GetString("ExternalAppNoneAbsolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à External app (optional).
        /// </summary>
        public static string ExternalAppOptional {
            get {
                return ResourceManager.GetString("ExternalAppOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à External apps.
        /// </summary>
        public static string ExternalApps {
            get {
                return ResourceManager.GetString("ExternalApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Checkbox.
        /// </summary>
        public static string FieldType_Checkbox {
            get {
                return ResourceManager.GetString("FieldType_Checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Checkbox grid.
        /// </summary>
        public static string FieldType_CheckboxGrid {
            get {
                return ResourceManager.GetString("FieldType_CheckboxGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Colour.
        /// </summary>
        public static string FieldType_Color {
            get {
                return ResourceManager.GetString("FieldType_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Detailed popup.
        /// </summary>
        public static string FieldType_DetailedPopup {
            get {
                return ResourceManager.GetString("FieldType_DetailedPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à D&amp;D conditions.
        /// </summary>
        public static string FieldType_DnDConditions {
            get {
                return ResourceManager.GetString("FieldType_DnDConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hit points.
        /// </summary>
        public static string FieldType_HitPoints {
            get {
                return ResourceManager.GetString("FieldType_HitPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Numeric.
        /// </summary>
        public static string FieldType_Numeric {
            get {
                return ResourceManager.GetString("FieldType_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stats.
        /// </summary>
        public static string FieldType_Stats {
            get {
                return ResourceManager.GetString("FieldType_Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Text.
        /// </summary>
        public static string FieldType_Text {
            get {
                return ResourceManager.GetString("FieldType_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Text grid.
        /// </summary>
        public static string FieldType_TextGrid {
            get {
                return ResourceManager.GetString("FieldType_TextGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Headers (one per line: Name: value).
        /// </summary>
        public static string HeadersOnePerLine {
            get {
                return ResourceManager.GetString("HeadersOnePerLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed.
        /// </summary>
        public static string LogFailed {
            get {
                return ResourceManager.GetString("LogFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Success.
        /// </summary>
        public static string LogSuccess {
            get {
                return ResourceManager.GetString("LogSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Meaning.
        /// </summary>
        public static string MeaningColumn {
            get {
                return ResourceManager.GetString("MeaningColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Method.
        /// </summary>
        public static string Method {
            get {
                return ResourceManager.GetString("Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New app.
        /// </summary>
        public static string NewAppName {
            get {
                return ResourceManager.GetString("NewAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New automation.
        /// </summary>
        public static string NewAutomationName {
            get {
                return ResourceManager.GetString("NewAutomationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Only when the value crosses this threshold.
        /// </summary>
        public static string OnlyWhenValueCrossesThreshold {
            get {
                return ResourceManager.GetString("OnlyWhenValueCrossesThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Option (empty = any option).
        /// </summary>
        public static string OptionEmptyAnyOption {
            get {
                return ResourceManager.GetString("OptionEmptyAnyOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à or.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à In HTTP URL, body, and header values, use.
        /// </summary>
        public static string PlaceholderCatalogueIntro1 {
            get {
                return ResourceManager.GetString("PlaceholderCatalogueIntro1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à placeholders to insert event data. Unknown or unavailable placeholders are replaced by an empty value. The available.
        /// </summary>
        public static string PlaceholderCatalogueIntro2 {
            get {
                return ResourceManager.GetString("PlaceholderCatalogueIntro2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à values depend on the selected trigger..
        /// </summary>
        public static string PlaceholderCatalogueIntro3 {
            get {
                return ResourceManager.GetString("PlaceholderCatalogueIntro3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Placeholder catalogue for HTTP templates.
        /// </summary>
        public static string PlaceholderCatalogueTitle {
            get {
                return ResourceManager.GetString("PlaceholderCatalogueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Placeholder.
        /// </summary>
        public static string PlaceholderColumn {
            get {
                return ResourceManager.GetString("PlaceholderColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Event family, for example.
        /// </summary>
        public static string PlaceholderMeaningCategory {
            get {
                return ResourceManager.GetString("PlaceholderMeaningCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Readable event name shown by DiceCombats..
        /// </summary>
        public static string PlaceholderMeaningDisplayName {
            get {
                return ResourceManager.GetString("PlaceholderMeaningDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unique event id..
        /// </summary>
        public static string PlaceholderMeaningId {
            get {
                return ResourceManager.GetString("PlaceholderMeaningId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à UTC timestamp in ISO-8601 format..
        /// </summary>
        public static string PlaceholderMeaningOccurredAt {
            get {
                return ResourceManager.GetString("PlaceholderMeaningOccurredAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Technical event type, for example.
        /// </summary>
        public static string PlaceholderMeaningType {
            get {
                return ResourceManager.GetString("PlaceholderMeaningType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Event metadata, available for every trigger.
        /// </summary>
        public static string PlaceholderMetadataTitle {
            get {
                return ResourceManager.GetString("PlaceholderMetadataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Placeholders.
        /// </summary>
        public static string PlaceholdersColumn {
            get {
                return ResourceManager.GetString("PlaceholdersColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All creature custom-field events.
        /// </summary>
        public static string PlaceholderWhenAllCreatureCustomFieldEvents {
            get {
                return ResourceManager.GetString("PlaceholderWhenAllCreatureCustomFieldEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Checkbox and condition options.
        /// </summary>
        public static string PlaceholderWhenCheckboxConditionOptions {
            get {
                return ResourceManager.GetString("PlaceholderWhenCheckboxConditionOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Combat timer started/paused/stopped.
        /// </summary>
        public static string PlaceholderWhenCombatTimer {
            get {
                return ResourceManager.GetString("PlaceholderWhenCombatTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Creature got/lost initiative.
        /// </summary>
        public static string PlaceholderWhenCreatureGotLostInitiative {
            get {
                return ResourceManager.GetString("PlaceholderWhenCreatureGotLostInitiative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Checkbox-grid and text-grid cells.
        /// </summary>
        public static string PlaceholderWhenGridCells {
            get {
                return ResourceManager.GetString("PlaceholderWhenGridCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hit-points field.
        /// </summary>
        public static string PlaceholderWhenHitPointsField {
            get {
                return ResourceManager.GetString("PlaceholderWhenHitPointsField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Most combat events.
        /// </summary>
        public static string PlaceholderWhenMostCombatEvents {
            get {
                return ResourceManager.GetString("PlaceholderWhenMostCombatEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Next creature in initiative.
        /// </summary>
        public static string PlaceholderWhenNextCreature {
            get {
                return ResourceManager.GetString("PlaceholderWhenNextCreature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Numeric, hit-points, and stats value changes.
        /// </summary>
        public static string PlaceholderWhenNumericHpStatsValueChanges {
            get {
                return ResourceManager.GetString("PlaceholderWhenNumericHpStatsValueChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Numeric field with maximum/unit enabled.
        /// </summary>
        public static string PlaceholderWhenNumericMaximumUnit {
            get {
                return ResourceManager.GetString("PlaceholderWhenNumericMaximumUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stats field.
        /// </summary>
        public static string PlaceholderWhenStatsField {
            get {
                return ResourceManager.GetString("PlaceholderWhenStatsField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User custom field saved/removed.
        /// </summary>
        public static string PlaceholderWhenUserCustomFieldSavedRemoved {
            get {
                return ResourceManager.GetString("PlaceholderWhenUserCustomFieldSavedRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Successfully saved automations, triggers and external apps.
        /// </summary>
        public static string SaveSuccessMessage {
            get {
                return ResourceManager.GetString("SaveSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Automations saved.
        /// </summary>
        public static string SaveSuccessTitle {
            get {
                return ResourceManager.GetString("SaveSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stat (empty = any stat).
        /// </summary>
        public static string StatEmptyAnyStat {
            get {
                return ResourceManager.GetString("StatEmptyAnyStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hit points (%).
        /// </summary>
        public static string ThresholdLabel_HitPointsThreshold {
            get {
                return ResourceManager.GetString("ThresholdLabel_HitPointsThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Numeric value.
        /// </summary>
        public static string ThresholdLabel_NumericThreshold {
            get {
                return ResourceManager.GetString("ThresholdLabel_NumericThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stat value.
        /// </summary>
        public static string ThresholdLabel_StatsThreshold {
            get {
                return ResourceManager.GetString("ThresholdLabel_StatsThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Value.
        /// </summary>
        public static string ThresholdLabel_Value {
            get {
                return ResourceManager.GetString("ThresholdLabel_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à above.
        /// </summary>
        public static string ThresholdOperator_Above {
            get {
                return ResourceManager.GetString("ThresholdOperator_Above", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à above or equal to.
        /// </summary>
        public static string ThresholdOperator_AboveOrEqual {
            get {
                return ResourceManager.GetString("ThresholdOperator_AboveOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à below.
        /// </summary>
        public static string ThresholdOperator_Below {
            get {
                return ResourceManager.GetString("ThresholdOperator_Below", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à below or equal to.
        /// </summary>
        public static string ThresholdOperator_BelowOrEqual {
            get {
                return ResourceManager.GetString("ThresholdOperator_BelowOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Timeout (ms).
        /// </summary>
        public static string TimeoutMs {
            get {
                return ResourceManager.GetString("TimeoutMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Automations.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trigger.
        /// </summary>
        public static string Trigger {
            get {
                return ResourceManager.GetString("Trigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Combat timer.
        /// </summary>
        public static string TriggerCategory_Combattimer {
            get {
                return ResourceManager.GetString("TriggerCategory_Combattimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Creatures.
        /// </summary>
        public static string TriggerCategory_Creatures {
            get {
                return ResourceManager.GetString("TriggerCategory_Creatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Custom fields.
        /// </summary>
        public static string TriggerCategory_Customfields {
            get {
                return ResourceManager.GetString("TriggerCategory_Customfields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Initiative.
        /// </summary>
        public static string TriggerCategory_Initiative {
            get {
                return ResourceManager.GetString("TriggerCategory_Initiative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Custom field changed.
        /// </summary>
        public static string TriggerDisplay_AnyCustomFieldChanged {
            get {
                return ResourceManager.GetString("TriggerDisplay_AnyCustomFieldChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Checkbox grid cell changed.
        /// </summary>
        public static string TriggerDisplay_CheckboxGridCellChanged {
            get {
                return ResourceManager.GetString("TriggerDisplay_CheckboxGridCellChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Checkbox grid cell checked.
        /// </summary>
        public static string TriggerDisplay_CheckboxGridCellChecked {
            get {
                return ResourceManager.GetString("TriggerDisplay_CheckboxGridCellChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Checkbox grid cell unchecked.
        /// </summary>
        public static string TriggerDisplay_CheckboxGridCellUnchecked {
            get {
                return ResourceManager.GetString("TriggerDisplay_CheckboxGridCellUnchecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Checkbox option changed.
        /// </summary>
        public static string TriggerDisplay_CheckboxOptionChanged {
            get {
                return ResourceManager.GetString("TriggerDisplay_CheckboxOptionChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Checkbox option checked.
        /// </summary>
        public static string TriggerDisplay_CheckboxOptionChecked {
            get {
                return ResourceManager.GetString("TriggerDisplay_CheckboxOptionChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Checkbox option unchecked.
        /// </summary>
        public static string TriggerDisplay_CheckboxOptionUnchecked {
            get {
                return ResourceManager.GetString("TriggerDisplay_CheckboxOptionUnchecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Checkbox text changed.
        /// </summary>
        public static string TriggerDisplay_CheckboxTextChanged {
            get {
                return ResourceManager.GetString("TriggerDisplay_CheckboxTextChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Colour field changed.
        /// </summary>
        public static string TriggerDisplay_ColourChanged {
            get {
                return ResourceManager.GetString("TriggerDisplay_ColourChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Condition option added.
        /// </summary>
        public static string TriggerDisplay_ConditionAdded {
            get {
                return ResourceManager.GetString("TriggerDisplay_ConditionAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Condition option removed.
        /// </summary>
        public static string TriggerDisplay_ConditionRemoved {
            get {
                return ResourceManager.GetString("TriggerDisplay_ConditionRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Condition option changed.
        /// </summary>
        public static string TriggerDisplay_ConditionsOptionChanged {
            get {
                return ResourceManager.GetString("TriggerDisplay_ConditionsOptionChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Creature got initiative.
        /// </summary>
        public static string TriggerDisplay_CreatureGotInitiative {
            get {
                return ResourceManager.GetString("TriggerDisplay_CreatureGotInitiative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Creature lost initiative.
        /// </summary>
        public static string TriggerDisplay_CreatureLostInitiative {
            get {
                return ResourceManager.GetString("TriggerDisplay_CreatureLostInitiative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Detailed popup opened.
        /// </summary>
        public static string TriggerDisplay_DetailedPopupOpened {
            get {
                return ResourceManager.GetString("TriggerDisplay_DetailedPopupOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hit points changed.
        /// </summary>
        public static string TriggerDisplay_HitPointsChanged {
            get {
                return ResourceManager.GetString("TriggerDisplay_HitPointsChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hit points decreased.
        /// </summary>
        public static string TriggerDisplay_HitPointsDamaged {
            get {
                return ResourceManager.GetString("TriggerDisplay_HitPointsDamaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hit points increased.
        /// </summary>
        public static string TriggerDisplay_HitPointsHealed {
            get {
                return ResourceManager.GetString("TriggerDisplay_HitPointsHealed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hit points crossed a percentage.
        /// </summary>
        public static string TriggerDisplay_HitPointsThreshold {
            get {
                return ResourceManager.GetString("TriggerDisplay_HitPointsThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Next creature in initiative.
        /// </summary>
        public static string TriggerDisplay_InitiativeNext {
            get {
                return ResourceManager.GetString("TriggerDisplay_InitiativeNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Initiative reset.
        /// </summary>
        public static string TriggerDisplay_InitiativeReset {
            get {
                return ResourceManager.GetString("TriggerDisplay_InitiativeReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Initiative sorted.
        /// </summary>
        public static string TriggerDisplay_InitiativeSorted {
            get {
                return ResourceManager.GetString("TriggerDisplay_InitiativeSorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Numeric field changed.
        /// </summary>
        public static string TriggerDisplay_NumericChanged {
            get {
                return ResourceManager.GetString("TriggerDisplay_NumericChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Numeric field decreased.
        /// </summary>
        public static string TriggerDisplay_NumericDecreased {
            get {
                return ResourceManager.GetString("TriggerDisplay_NumericDecreased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Numeric field increased.
        /// </summary>
        public static string TriggerDisplay_NumericIncreased {
            get {
                return ResourceManager.GetString("TriggerDisplay_NumericIncreased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Numeric field reached max value.
        /// </summary>
        public static string TriggerDisplay_NumericReachedMaxValue {
            get {
                return ResourceManager.GetString("TriggerDisplay_NumericReachedMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Numeric field crossed a value.
        /// </summary>
        public static string TriggerDisplay_NumericThreshold {
            get {
                return ResourceManager.GetString("TriggerDisplay_NumericThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stat value changed.
        /// </summary>
        public static string TriggerDisplay_StatsChanged {
            get {
                return ResourceManager.GetString("TriggerDisplay_StatsChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stat value decreased.
        /// </summary>
        public static string TriggerDisplay_StatsDecreased {
            get {
                return ResourceManager.GetString("TriggerDisplay_StatsDecreased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stat value increased.
        /// </summary>
        public static string TriggerDisplay_StatsIncreased {
            get {
                return ResourceManager.GetString("TriggerDisplay_StatsIncreased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stat crossed a value.
        /// </summary>
        public static string TriggerDisplay_StatsThreshold {
            get {
                return ResourceManager.GetString("TriggerDisplay_StatsThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Text field changed.
        /// </summary>
        public static string TriggerDisplay_TextChanged {
            get {
                return ResourceManager.GetString("TriggerDisplay_TextChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Text grid cell changed.
        /// </summary>
        public static string TriggerDisplay_TextGridCellChanged {
            get {
                return ResourceManager.GetString("TriggerDisplay_TextGridCellChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Timer paused.
        /// </summary>
        public static string TriggerDisplay_TimerPaused {
            get {
                return ResourceManager.GetString("TriggerDisplay_TimerPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Timer started.
        /// </summary>
        public static string TriggerDisplay_TimerStarted {
            get {
                return ResourceManager.GetString("TriggerDisplay_TimerStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Timer stopped.
        /// </summary>
        public static string TriggerDisplay_TimerStopped {
            get {
                return ResourceManager.GetString("TriggerDisplay_TimerStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User custom field removed.
        /// </summary>
        public static string TriggerDisplay_UserCustomFieldRemoved {
            get {
                return ResourceManager.GetString("TriggerDisplay_UserCustomFieldRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User custom field saved.
        /// </summary>
        public static string TriggerDisplay_UserCustomFieldSaved {
            get {
                return ResourceManager.GetString("TriggerDisplay_UserCustomFieldSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à any creature.
        /// </summary>
        public static string TriggerSummaryAnyCreature {
            get {
                return ResourceManager.GetString("TriggerSummaryAnyCreature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à any matching field.
        /// </summary>
        public static string TriggerSummaryAnyMatchingField {
            get {
                return ResourceManager.GetString("TriggerSummaryAnyMatchingField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à any option.
        /// </summary>
        public static string TriggerSummaryAnyOption {
            get {
                return ResourceManager.GetString("TriggerSummaryAnyOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à any stat.
        /// </summary>
        public static string TriggerSummaryAnyStat {
            get {
                return ResourceManager.GetString("TriggerSummaryAnyStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Triggers for {0}..
        /// </summary>
        public static string TriggerSummaryCreatureFilter {
            get {
                return ResourceManager.GetString("TriggerSummaryCreatureFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Triggers on: {0}..
        /// </summary>
        public static string TriggerSummaryDefault {
            get {
                return ResourceManager.GetString("TriggerSummaryDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à field “{0}”.
        /// </summary>
        public static string TriggerSummaryField {
            get {
                return ResourceManager.GetString("TriggerSummaryField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Triggers when {0} changes on {1}..
        /// </summary>
        public static string TriggerSummaryFieldChanged {
            get {
                return ResourceManager.GetString("TriggerSummaryFieldChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Triggers when {0} on {1} becomes equal to its max value..
        /// </summary>
        public static string TriggerSummaryNumericReachedMaxValue {
            get {
                return ResourceManager.GetString("TriggerSummaryNumericReachedMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à option “{0}”.
        /// </summary>
        public static string TriggerSummaryOption {
            get {
                return ResourceManager.GetString("TriggerSummaryOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Triggers when {0} in {1} changes on {2}..
        /// </summary>
        public static string TriggerSummaryOptionChanged {
            get {
                return ResourceManager.GetString("TriggerSummaryOptionChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à stat “{0}”.
        /// </summary>
        public static string TriggerSummaryStat {
            get {
                return ResourceManager.GetString("TriggerSummaryStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Triggers when {0} in {1} changes on {2}..
        /// </summary>
        public static string TriggerSummaryStatChanged {
            get {
                return ResourceManager.GetString("TriggerSummaryStatChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Triggers when {0} on {1} is {2} {3}..
        /// </summary>
        public static string TriggerSummaryThreshold {
            get {
                return ResourceManager.GetString("TriggerSummaryThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If nothing happens, check that the automation and the external app are enabled, press Save, then perform the action in Combat Manager again. If a log entry appears with a failure, verify the URL, HTTP method, timeout, and that the external application is running and reachable..
        /// </summary>
        public static string TroubleshootingText {
            get {
                return ResourceManager.GetString("TroubleshootingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Troubleshooting.
        /// </summary>
        public static string TroubleshootingTitle {
            get {
                return ResourceManager.GetString("TroubleshootingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à When.
        /// </summary>
        public static string When {
            get {
                return ResourceManager.GetString("When", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à When available.
        /// </summary>
        public static string WhenAvailableColumn {
            get {
                return ResourceManager.GetString("WhenAvailableColumn", resourceCulture);
            }
        }
    }
}
