//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiceCombats.Resources.Localization {
    using System;
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CreatureCustomFieldsEditor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreatureCustomFieldsEditor() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiceCombats.Resources.Localization.CreatureCustomFieldsEditor", typeof(CreatureCustomFieldsEditor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AddAdditionalFieldsTitle {
            get {
                return ResourceManager.GetString("AddAdditionalFieldsTitle", resourceCulture);
            }
        }
        
        internal static string AddField {
            get {
                return ResourceManager.GetString("AddField", resourceCulture);
            }
        }
        
        internal static string AssistanceCheckboxField {
            get {
                return ResourceManager.GetString("AssistanceCheckboxField", resourceCulture);
            }
        }
        
        internal static string AssistanceCheckboxField2 {
            get {
                return ResourceManager.GetString("AssistanceCheckboxField2", resourceCulture);
            }
        }
        
        internal static string AssistanceCheckboxField3 {
            get {
                return ResourceManager.GetString("AssistanceCheckboxField3", resourceCulture);
            }
        }
        
        internal static string AssistanceCheckboxGridField {
            get {
                return ResourceManager.GetString("AssistanceCheckboxGridField", resourceCulture);
            }
        }
        
        internal static string AssistanceCheckboxGridField2 {
            get {
                return ResourceManager.GetString("AssistanceCheckboxGridField2", resourceCulture);
            }
        }
        
        internal static string AssistanceColorField {
            get {
                return ResourceManager.GetString("AssistanceColorField", resourceCulture);
            }
        }
        
        internal static string AssistanceConditionsField {
            get {
                return ResourceManager.GetString("AssistanceConditionsField", resourceCulture);
            }
        }
        
        internal static string AssistanceConditionsField2 {
            get {
                return ResourceManager.GetString("AssistanceConditionsField2", resourceCulture);
            }
        }
        
        internal static string AssistanceFieldTitle {
            get {
                return ResourceManager.GetString("AssistanceFieldTitle", resourceCulture);
            }
        }
        
        internal static string AssistanceGeneralExamplesDesc {
            get {
                return ResourceManager.GetString("AssistanceGeneralExamplesDesc", resourceCulture);
            }
        }
        
        internal static string AssistanceGeneralExamplesTitle {
            get {
                return ResourceManager.GetString("AssistanceGeneralExamplesTitle", resourceCulture);
            }
        }
        
        internal static string AssistanceGeneralSharedFieldsDesc {
            get {
                return ResourceManager.GetString("AssistanceGeneralSharedFieldsDesc", resourceCulture);
            }
        }
        
        internal static string AssistanceGeneralSharedFieldsTitle {
            get {
                return ResourceManager.GetString("AssistanceGeneralSharedFieldsTitle", resourceCulture);
            }
        }
        
        internal static string AssistanceHitPointsField {
            get {
                return ResourceManager.GetString("AssistanceHitPointsField", resourceCulture);
            }
        }
        
        internal static string AssistanceNumericField {
            get {
                return ResourceManager.GetString("AssistanceNumericField", resourceCulture);
            }
        }
        
        internal static string AssistanceStatsField {
            get {
                return ResourceManager.GetString("AssistanceStatsField", resourceCulture);
            }
        }
        
        internal static string AssistanceStatsField2 {
            get {
                return ResourceManager.GetString("AssistanceStatsField2", resourceCulture);
            }
        }
        
        internal static string AssistanceTextField {
            get {
                return ResourceManager.GetString("AssistanceTextField", resourceCulture);
            }
        }
        
        internal static string AssistanceTextGridField {
            get {
                return ResourceManager.GetString("AssistanceTextGridField", resourceCulture);
            }
        }
        
        internal static string AssistanceUserCustomFieldDesc {
            get {
                return ResourceManager.GetString("AssistanceUserCustomFieldDesc", resourceCulture);
            }
        }
        
        internal static string AssistanceUserCustomFieldTitle {
            get {
                return ResourceManager.GetString("AssistanceUserCustomFieldTitle", resourceCulture);
            }
        }
        
        internal static string AssitanceGeneral1 {
            get {
                return ResourceManager.GetString("AssitanceGeneral1", resourceCulture);
            }
        }
        
        internal static string CustomFieldBtn {
            get {
                return ResourceManager.GetString("CustomFieldBtn", resourceCulture);
            }
        }
        
        internal static string FieldRemove {
            get {
                return ResourceManager.GetString("FieldRemove", resourceCulture);
            }
        }
        
        internal static string FieldType {
            get {
                return ResourceManager.GetString("FieldType", resourceCulture);
            }
        }
        
        internal static string MoveBackward {
            get {
                return ResourceManager.GetString("MoveBackward", resourceCulture);
            }
        }
        
        internal static string MoveForward {
            get {
                return ResourceManager.GetString("MoveForward", resourceCulture);
            }
        }
        
        internal static string SharedField {
            get {
                return ResourceManager.GetString("SharedField", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à A composite, searchable popup....
        /// </summary>
        internal static string AssistanceDetailedPopupField {
            get {
                return ResourceManager.GetString("AssistanceDetailedPopupField", resourceCulture);
            }
        }
    }
}
