//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiceCombats.Resources.Localization {
    using System;
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CreatureCustomFieldRenderer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreatureCustomFieldRenderer() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiceCombats.Resources.Localization.CreatureCustomFieldRenderer", typeof(CreatureCustomFieldRenderer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string CBFieldAddOption {
            get {
                return ResourceManager.GetString("CBFieldAddOption", resourceCulture);
            }
        }
        
        internal static string CBFieldShowFieldName {
            get {
                return ResourceManager.GetString("CBFieldShowFieldName", resourceCulture);
            }
        }
        
        internal static string CBFieldShowTextFields {
            get {
                return ResourceManager.GetString("CBFieldShowTextFields", resourceCulture);
            }
        }
        
        internal static string CBFieldTextLabels {
            get {
                return ResourceManager.GetString("CBFieldTextLabels", resourceCulture);
            }
        }
        
        internal static string CBGridColumnLabels {
            get {
                return ResourceManager.GetString("CBGridColumnLabels", resourceCulture);
            }
        }
        
        internal static string CBGridColumnName {
            get {
                return ResourceManager.GetString("CBGridColumnName", resourceCulture);
            }
        }
        
        internal static string CBGridHorizontal {
            get {
                return ResourceManager.GetString("CBGridHorizontal", resourceCulture);
            }
        }
        
        internal static string CBGridRowLabels {
            get {
                return ResourceManager.GetString("CBGridRowLabels", resourceCulture);
            }
        }
        
        internal static string CBGridRowName {
            get {
                return ResourceManager.GetString("CBGridRowName", resourceCulture);
            }
        }
        
        internal static string CBGridVertical {
            get {
                return ResourceManager.GetString("CBGridVertical", resourceCulture);
            }
        }
        
        internal static string ColorPickerName {
            get {
                return ResourceManager.GetString("ColorPickerName", resourceCulture);
            }
        }
        
        internal static string CreatureStatsCount {
            get {
                return ResourceManager.GetString("CreatureStatsCount", resourceCulture);
            }
        }
        
        internal static string CreatureStatsKeepValuesEditable {
            get {
                return ResourceManager.GetString("CreatureStatsKeepValuesEditable", resourceCulture);
            }
        }
        
        internal static string CreatureStatsStatLabel {
            get {
                return ResourceManager.GetString("CreatureStatsStatLabel", resourceCulture);
            }
        }
        
        internal static string CustomFieldBtn {
            get {
                return ResourceManager.GetString("CustomFieldBtn", resourceCulture);
            }
        }
        
        internal static string DnDConditionAddCondition {
            get {
                return ResourceManager.GetString("DnDConditionAddCondition", resourceCulture);
            }
        }
        
        internal static string DnDConditionMinimize {
            get {
                return ResourceManager.GetString("DnDConditionMinimize", resourceCulture);
            }
        }
        
        internal static string FieldNameLabel {
            get {
                return ResourceManager.GetString("FieldNameLabel", resourceCulture);
            }
        }
        
        internal static string HP {
            get {
                return ResourceManager.GetString("HP", resourceCulture);
            }
        }
        
        internal static string MaxHPLabel {
            get {
                return ResourceManager.GetString("MaxHPLabel", resourceCulture);
            }
        }
        
        internal static string NonEditableField {
            get {
                return ResourceManager.GetString("NonEditableField", resourceCulture);
            }
        }
        
        internal static string OptionLabel {
            get {
                return ResourceManager.GetString("OptionLabel", resourceCulture);
            }
        }
        
        internal static string SharedField {
            get {
                return ResourceManager.GetString("SharedField", resourceCulture);
            }
        }
        
        internal static string TextGridColumnLabels {
            get {
                return ResourceManager.GetString("TextGridColumnLabels", resourceCulture);
            }
        }
        
        internal static string TextGridColumnName {
            get {
                return ResourceManager.GetString("TextGridColumnName", resourceCulture);
            }
        }
        
        internal static string TextGridHorizontal {
            get {
                return ResourceManager.GetString("TextGridHorizontal", resourceCulture);
            }
        }
        
        internal static string TextGridRowLabels {
            get {
                return ResourceManager.GetString("TextGridRowLabels", resourceCulture);
            }
        }
        
        internal static string TextGridRowName {
            get {
                return ResourceManager.GetString("TextGridRowName", resourceCulture);
            }
        }
        
        internal static string TextGridShowLabel {
            get {
                return ResourceManager.GetString("TextGridShowLabel", resourceCulture);
            }
        }
        
        internal static string TextGridVertical {
            get {
                return ResourceManager.GetString("TextGridVertical", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit contents.
        /// </summary>
        internal static string DetailedPopupEditButton {
            get {
                return ResourceManager.GetString("DetailedPopupEditButton", resourceCulture);
            }
        }
    }
}
