//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiceCombats.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CreatureCustomFieldRenderer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreatureCustomFieldRenderer() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiceCombats.Resources.Localization.CreatureCustomFieldRenderer", typeof(CreatureCustomFieldRenderer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add option.
        /// </summary>
        internal static string CBFieldAddOption {
            get {
                return ResourceManager.GetString("CBFieldAddOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show text fields.
        /// </summary>
        internal static string CBFieldShowTextFields {
            get {
                return ResourceManager.GetString("CBFieldShowTextFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Text labels.
        /// </summary>
        internal static string CBFieldTextLabels {
            get {
                return ResourceManager.GetString("CBFieldTextLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Column labels.
        /// </summary>
        internal static string CBGridColumnLabels {
            get {
                return ResourceManager.GetString("CBGridColumnLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Column name.
        /// </summary>
        internal static string CBGridColumnName {
            get {
                return ResourceManager.GetString("CBGridColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Horizontal.
        /// </summary>
        internal static string CBGridHorizontal {
            get {
                return ResourceManager.GetString("CBGridHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Row labels.
        /// </summary>
        internal static string CBGridRowLabels {
            get {
                return ResourceManager.GetString("CBGridRowLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Row name.
        /// </summary>
        internal static string CBGridRowName {
            get {
                return ResourceManager.GetString("CBGridRowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vertical.
        /// </summary>
        internal static string CBGridVertical {
            get {
                return ResourceManager.GetString("CBGridVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Basic Color Picker.
        /// </summary>
        internal static string ColorPickerName {
            get {
                return ResourceManager.GetString("ColorPickerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stats count.
        /// </summary>
        internal static string CreatureStatsCount {
            get {
                return ResourceManager.GetString("CreatureStatsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Keep values editable.
        /// </summary>
        internal static string CreatureStatsKeepValuesEditable {
            get {
                return ResourceManager.GetString("CreatureStatsKeepValuesEditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stat label.
        /// </summary>
        internal static string CreatureStatsStatLabel {
            get {
                return ResourceManager.GetString("CreatureStatsStatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Custom field.
        /// </summary>
        internal static string CustomFieldBtn {
            get {
                return ResourceManager.GetString("CustomFieldBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add condition.
        /// </summary>
        internal static string DnDConditionAddCondition {
            get {
                return ResourceManager.GetString("DnDConditionAddCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Minimize.
        /// </summary>
        internal static string DnDConditionMinimize {
            get {
                return ResourceManager.GetString("DnDConditionMinimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Field name.
        /// </summary>
        internal static string FieldNameLabel {
            get {
                return ResourceManager.GetString("FieldNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à HP.
        /// </summary>
        internal static string HP {
            get {
                return ResourceManager.GetString("HP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Max HP.
        /// </summary>
        internal static string MaxHPLabel {
            get {
                return ResourceManager.GetString("MaxHPLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This field cannot be edited.
        /// </summary>
        internal static string NonEditableField {
            get {
                return ResourceManager.GetString("NonEditableField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Option label.
        /// </summary>
        internal static string OptionLabel {
            get {
                return ResourceManager.GetString("OptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Shared.
        /// </summary>
        internal static string SharedField {
            get {
                return ResourceManager.GetString("SharedField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Column labels.
        /// </summary>
        internal static string TextGridColumnLabels {
            get {
                return ResourceManager.GetString("TextGridColumnLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Column name.
        /// </summary>
        internal static string TextGridColumnName {
            get {
                return ResourceManager.GetString("TextGridColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Horizontal.
        /// </summary>
        internal static string TextGridHorizontal {
            get {
                return ResourceManager.GetString("TextGridHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Row labels.
        /// </summary>
        internal static string TextGridRowLabels {
            get {
                return ResourceManager.GetString("TextGridRowLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Row name.
        /// </summary>
        internal static string TextGridRowName {
            get {
                return ResourceManager.GetString("TextGridRowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show label.
        /// </summary>
        internal static string TextGridShowLabel {
            get {
                return ResourceManager.GetString("TextGridShowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vertical.
        /// </summary>
        internal static string TextGridVertical {
            get {
                return ResourceManager.GetString("TextGridVertical", resourceCulture);
            }
        }
    }
}
