//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiceCombats.Resources.Localization {
    using System;
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DetailedPopupFieldPopup {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DetailedPopupFieldPopup() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiceCombats.Resources.Localization.DetailedPopupFieldPopup", typeof(DetailedPopupFieldPopup).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string DetailedPopupShowEditorHelp => ResourceManager.GetString("DetailedPopupShowEditorHelp", resourceCulture);
        internal static string DetailedPopupOverviewTitle => ResourceManager.GetString("DetailedPopupOverviewTitle", resourceCulture);
        internal static string DetailedPopupOverviewBody => ResourceManager.GetString("DetailedPopupOverviewBody", resourceCulture);
        internal static string DetailedPopupTextTitle => ResourceManager.GetString("DetailedPopupTextTitle", resourceCulture);
        internal static string DetailedPopupTextBody => ResourceManager.GetString("DetailedPopupTextBody", resourceCulture);
        internal static string DetailedPopupMarkdownTitle => ResourceManager.GetString("DetailedPopupMarkdownTitle", resourceCulture);
        internal static string DetailedPopupMarkdownBody => ResourceManager.GetString("DetailedPopupMarkdownBody", resourceCulture);
        internal static string DetailedPopupPdfTitle => ResourceManager.GetString("DetailedPopupPdfTitle", resourceCulture);
        internal static string DetailedPopupPdfBody => ResourceManager.GetString("DetailedPopupPdfBody", resourceCulture);
        internal static string DetailedPopupHtmlHowItWorksTitle => ResourceManager.GetString("DetailedPopupHtmlHowItWorksTitle", resourceCulture);
        internal static string DetailedPopupHtmlHowItWorksBody => ResourceManager.GetString("DetailedPopupHtmlHowItWorksBody", resourceCulture);
        internal static string DetailedPopupHtmlTipsTitle => ResourceManager.GetString("DetailedPopupHtmlTipsTitle", resourceCulture);
        internal static string DetailedPopupHtmlTipsBody => ResourceManager.GetString("DetailedPopupHtmlTipsBody", resourceCulture);
        internal static string DetailedPopupHtmlQuickStartTitle => ResourceManager.GetString("DetailedPopupHtmlQuickStartTitle", resourceCulture);
        internal static string DetailedPopupHtmlQuickStartBody => ResourceManager.GetString("DetailedPopupHtmlQuickStartBody", resourceCulture);
        internal static string DetailedPopupTroubleshootingTitle => ResourceManager.GetString("DetailedPopupTroubleshootingTitle", resourceCulture);
        internal static string DetailedPopupTroubleshootingBody => ResourceManager.GetString("DetailedPopupTroubleshootingBody", resourceCulture);
        internal static string DetailedPopupInlineHelpHtml => ResourceManager.GetString("DetailedPopupInlineHelpHtml", resourceCulture);
        internal static string DetailedPopupDeleteTooltip => ResourceManager.GetString("DetailedPopupDeleteTooltip", resourceCulture);
        internal static string DetailedPopupDeleteButton => ResourceManager.GetString("DetailedPopupDeleteButton", resourceCulture);
        internal static string DetailedPopupContentNameLabel => ResourceManager.GetString("DetailedPopupContentNameLabel", resourceCulture);
        internal static string DetailedPopupKindLabel => ResourceManager.GetString("DetailedPopupKindLabel", resourceCulture);
        internal static string DetailedPopupKindTextLabel => ResourceManager.GetString("DetailedPopupKindTextLabel", resourceCulture);
        internal static string DetailedPopupKindMarkdownLabel => ResourceManager.GetString("DetailedPopupKindMarkdownLabel", resourceCulture);
        internal static string DetailedPopupKindHtmlLabel => ResourceManager.GetString("DetailedPopupKindHtmlLabel", resourceCulture);
        internal static string DetailedPopupKindPdfLabel => ResourceManager.GetString("DetailedPopupKindPdfLabel", resourceCulture);
        internal static string DetailedPopupTextContentLabel => ResourceManager.GetString("DetailedPopupTextContentLabel", resourceCulture);
        internal static string DetailedPopupMarkdownContentLabel => ResourceManager.GetString("DetailedPopupMarkdownContentLabel", resourceCulture);
        internal static string DetailedPopupSelectorLabel => ResourceManager.GetString("DetailedPopupSelectorLabel", resourceCulture);
        internal static string DetailedPopupTemplateLabel => ResourceManager.GetString("DetailedPopupTemplateLabel", resourceCulture);
        internal static string DetailedPopupCssLabel => ResourceManager.GetString("DetailedPopupCssLabel", resourceCulture);
        internal static string DetailedPopupMapJsonLabel => ResourceManager.GetString("DetailedPopupMapJsonLabel", resourceCulture);
        internal static string DetailedPopupHtmlSourceInlineLabel => ResourceManager.GetString("DetailedPopupHtmlSourceInlineLabel", resourceCulture);
        internal static string DetailedPopupHtmlSourceFileLabel => ResourceManager.GetString("DetailedPopupHtmlSourceFileLabel", resourceCulture);
        internal static string DetailedPopupHtmlContentLabel => ResourceManager.GetString("DetailedPopupHtmlContentLabel", resourceCulture);
        internal static string DetailedPopupFilePathLabel => ResourceManager.GetString("DetailedPopupFilePathLabel", resourceCulture);
        internal static string DetailedPopupPickFileButton => ResourceManager.GetString("DetailedPopupPickFileButton", resourceCulture);
        internal static string DetailedPopupLoadedBytesCaption => ResourceManager.GetString("DetailedPopupLoadedBytesCaption", resourceCulture);
        internal static string DetailedPopupPdfInlineHelp => ResourceManager.GetString("DetailedPopupPdfInlineHelp", resourceCulture);
        internal static string DetailedPopupSearchPlaceholder => ResourceManager.GetString("DetailedPopupSearchPlaceholder", resourceCulture);
        internal static string DetailedPopupToggleGridTooltip => ResourceManager.GetString("DetailedPopupToggleGridTooltip", resourceCulture);
        internal static string DetailedPopupDeleteDialogTitle => ResourceManager.GetString("DetailedPopupDeleteDialogTitle", resourceCulture);
        internal static string DetailedPopupDeleteDialogMessage => ResourceManager.GetString("DetailedPopupDeleteDialogMessage", resourceCulture);
        internal static string DetailedPopupDeleteDialogYes => ResourceManager.GetString("DetailedPopupDeleteDialogYes", resourceCulture);
        internal static string DetailedPopupDeleteDialogCancel => ResourceManager.GetString("DetailedPopupDeleteDialogCancel", resourceCulture);
        internal static string DetailedPopupAddNewContentButton => ResourceManager.GetString("DetailedPopupAddNewContentButton", resourceCulture);
    }
}
